import { CustomersPage } from "./CustomersPage";
import { DashboardPage } from "./DashboardPage";
import { FunnelPage } from "./FunnelPage";
import { ProductsPage } from "./ProductsPage";
import { TrafficPage } from "./TrafficPage";
export { CustomersPage };
export { DashboardPage };
export { FunnelPage };
export { ProductsPage };
export { TrafficPage };
