services:
  - type: web
    name: ecommerce-dashboard-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
